root: true
parserOptions:
  sourceType: "module"
env:
  es2022: true
  browser: true
extends:
  eslint:recommended
overrides:
- files:
  - "*.spec.js"
  env:
    mocha: true
  globals:
    expect: true
- files:
  - "*.cjs"
  env:
    browser: false
    node: true
